### ISSUE TITLE
Jumping to numbered suggestions doesn't insert the item

### ISSUE THREAD

**Issue by kosivantsov** [transducens/Forecat-OmegaT#1]
I'm using 1.0b in OmegaT 4.1.5 (built from /trunk). When Forecat gives several suggestions, jumping to any of them using Alt + Number highlights the desired item, closes autocompleter popup, and inserts a line break instead of the suggested item. I was expecting to just get the item highlighted, or at least get it inserted.

**Comment by dtr5** [comment]
Hi Kos, 

sadly, Forecat-OmegaT is not compatible with OmegaT 4.1.5. I patched Forcat-OmegaT to OmegaT 4.1.0 so it would run with that version, but this release is mainly untested, and this bug may be present on that version too.

When I looked at OmegaT 4 some months ago, I saw that the developing team was introducing changes  that often broke the APIs the plugin is using, so I decided to wait until a Stable 4.x version got released (likely, after a feature freeze).

If you really want to use Forecat-OmegaT with OmegaT 4, I will have a look at it. Otherwise, please use it with the Standard version instead.

**Comment by kosivantsov** [comment]
Well, I can live with the issue. Forecat gives me productivity boost despite this and several other bugs. Thank you a heap for developing it. Switching to 3.6 is not much of an option for me, most of my project utilize team project mappings introduced in 4.x. But as to the freeze I would suggest to discuss it with Didier and Aaron. As far as I know 4.x is almost Stable-ready, and it would have been released as Stable if the documentation was ready.

**Comment by dtr5** [comment]
Please, report the other bugs so I can also have a look at them.

**Comment by kosivantsov** [comment]
>Please, report the other bugs so I can also have a look at them.
>

I posted one, as you've already seen. There was another one, but I don't seem
to be able to reproduce it anymore. I'll do some more testings and report back
when I'm positive as to how to "achieve" the bug.

**Comment by dtr5** [comment]
Can you describe that issue? You might not be able to reproduce it, but it may be something I found before.

**Comment by kosivantsov** [comment]
it was [#3](https://github.com/transducens/Forecat-OmegaT/issues/3)

**Comment by dtr5** [comment]
Marking as closed, f7fd78b3feb83151286658428620e4dee4c42525 fixes this bug.

There is a new jar file in /build, if you do not want to compile it from scratch. Mind that you will have to manually delete the old file, as the it was named "incorrectly" omegat-forecat.jar, and the new one is forecat-omegat.jar.
